### ISSUE TITLE
API 'android.registerTransform' is removed.

### ISSUE THREAD

**Issue by wangkai147** [HuolalaTech/hll-wp-therouter-android#22]
aused by: com.android.builder.errors.EvalIssueException: API 'android.registerTransform' is removed.

**Comment by kymjs** [comment]
待支持，Gradle7 移除了 Transform API

**Comment by sunshuai212** [comment]
agp7.0开始只是标记即将废弃，8.0才会正式移除掉

**Comment by kymjs** [comment]
代码层面目前`TheRouter`已兼容，详细进度可关注`apg8`分支。
但由于AGP8现在都还是alpha6的版本，不确定将来是否还会发生API变动，直到AGP8退出正式版，我们才会发布对应TheRouter插件版本。

**Comment by vindinser** [comment]
Could not apply requested plugin [id: 'cn.therouter', version: '1.3.0-rc4'] as it does not provide a plugin with id 'cn.therouter'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s). > Plugin with id 'cn.therouter' not found.

alias(libs.plugins.therouter.plugin)
therouter = "1.3.0-rc4"
therouter-plugin = { id = "cn.therouter", version.ref = "therouter" }

**Comment by vindinser** [comment]
**环境**
- Gradle 版本: 8.11.1
- TheRouter 版本: 1.3.0-rc4
- JDK 版本: 17

**问题**
尝试所有已知插件 ID 都无法应用插件：
- cn.therouter
- com.therouter
- therouter
- cn.therouter.agp8

**已尝试解决方案**
1. 通过 buildscript 直接添加
2. 使用 apply plugin = "..." 方式
3. 直接应用插件类
4. 多仓库尝试 (sonatype, mavenCentral, Huawei)
5. 多种版本 (1.2.4, 1.3.0-rc4, 1.1.1)

**错误日志**
Could not apply requested plugin [id: 'cn.therouter', version: '1.3.0-rc4'] as it does not provide a plugin with id 'cn.therouter'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).

**附加信息**
alias(libs.plugins.therouter.plugin)
therouter = "1.3.0-rc4"
therouter-plugin = { id = "cn.therouter", version.ref = "therouter" }

**Comment by fansangg** [comment]
> **环境**
> 
> * Gradle 版本: 8.11.1
> * TheRouter 版本: 1.3.0-rc4
> * JDK 版本: 17
> 
> **问题** 尝试所有已知插件 ID 都无法应用插件：
> 
> * cn.therouter
> * com.therouter
> * therouter
> * cn.therouter.agp8
> 
> **已尝试解决方案**
> 
> 1. 通过 buildscript 直接添加
> 2. 使用 apply plugin = "..." 方式
> 3. 直接应用插件类
> 4. 多仓库尝试 (sonatype, mavenCentral, Huawei)
> 5. 多种版本 (1.2.4, 1.3.0-rc4, 1.1.1)
> 
> **错误日志** Could not apply requested plugin [id: 'cn.therouter', version: '1.3.0-rc4'] as it does not provide a plugin with id 'cn.therouter'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> 
> **附加信息** alias(libs.plugins.therouter.plugin) therouter = "1.3.0-rc4" therouter-plugin = { id = "cn.therouter", version.ref = "therouter" }

Could not apply requested plugin [id: 'cn.therouter', version: '1.3.0'] as it does not provide a plugin with id 'cn.therouter'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'cn.therouter' not found.

你后面怎么处理的？
